# value
LED_FLASHING_DELAY_MS = 15
I2C_LOOP_DELAY_MS = 50

# onboard led
ONBOARD_LED_PIN = 25

# config pin
WAIT_JETSON_PIN = 28

# motor define
MOTOR_PWM_FREQ = 60

MOTOR_L_F_PIN = 6
MOTOR_L_B_PIN = 7
MOTOR_R_F_PIN = 8
MOTOR_R_B_PIN = 9

# UART define
UART_CHANNEL = 1
UART_TX_PIN = 4
UART_RX_PIN = 5

UART_BAUDRAT = 115200

# I2C Slave define
I2C_SL_CH = 0
I2C_SL_SDA_PIN = 4
I2C_SL_SCL_PIN = 5
I2C_SL_ADDR = 0x50

# Ultrasonic Sensor
U_SENSOR_TRIG_PIN = 0
U_SENSOR_ECHO_PIN = 1