version: '2.3'

services:
  ros-master:
    image: ros:kinetic-ros-base
    container_name: ros-master
    command: stdbuf -o L roscore
    ports:
      - "11311:11311"
    networks:
      - ros
    restart: always

  talker:
    image: ros:kinetic-ros-base
    depends_on:
      - ros-master
    environment:
      - "ROS_MASTER_URI=http://ros-master:11311"
      - "ROS_HOSTNAME=talker"
    command: stdbuf -o L rostopic pub /chatter std_msgs/String "hello" -r 1
    networks:
      - ros
    restart: always
    
  listener:
    image: ros:kinetic-ros-base
    depends_on:
      - ros-master
    environment:
      - "ROS_MASTER_URI=http://ros-master:11311"
      - "ROS_HOSTNAME=listener"
    command: stdbuf -o L rostopic echo /chatter
    networks:
      - ros
    restart: always
    
networks:
  ros:
    driver: bridge