version: '2.3'
services:
  home-watcher:
    build:
      context: .
      dockerfile: Dockerfile.armhf
    image: home-watcher:latest
    container_name: home-watcher
    restart: always
    command: uwsgi --ini uwsgi.ini
    ports:
      - "9001:8080"
    networks:
      - home-watcher
    mem_limit: 500M
    volumes:
      - ./:/app
      - /home/jim/motioneye/record/MainDoor/:/app/videos
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      RESIZE_FACTOR: 1
  
networks:
  home-watcher:
    name: home-watcher-network
    driver: bridge