FROM dorajim15/face-recognition:1.3.0-v1

RUN groupadd -r watcher
RUN useradd -r -u 1010 -g watcher watcher

WORKDIR /app
COPY . /app
RUN chown -R watcher /app

USER watcher
ENTRYPOINT ["python", "home_watcher.py"]