version: '2.3'
services:
  home-watcher-videos:
    image: nginx:stable-alpine
    container_name: home-watcher-videos
    restart: always
    ports:
      - "9002:8080"
    networks:
      - home-watcher-videos
    mem_limit: 500M
    volumes:
        - ./video-nginx.conf:/etc/nginx/conf.d/default.conf
        - /home/jim/motioneye/record/MainDoor/:/videos
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      RESIZE_FACTOR: 1
  
networks:
  home-watcher-videos:
    name: home-watcher-videos-network
    driver: bridge