FROM dorajim15/face-recognition-opencv-python:1.3.0_4.5.1.48_arm64
EXPOSE 8080

# RUN groupadd -r watcher
# RUN useradd -r -u 1010 -g watcher watcher
RUN pip install requests flask uwsgi

WORKDIR /app
COPY . /app
# RUN chown -R watcher /app
